source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LwCollectionViewCombineLayout_Example', :exclusive => true do
  pod "LwCollectionViewCombineLayout", :path => "../"
end

target 'LwCollectionViewCombineLayout_Tests', :exclusive => true do
  pod "LwCollectionViewCombineLayout", :path => "../"

  pod 'Kiwi'
end
